apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: github-arc-controller
  namespace: flux-system
spec:
  interval: 1h
  type: oci
  url: oci://ghcr.io/actions/actions-runner-controller-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: github-arc-controller
  namespace: flux-system
spec:
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: 0.9.0
      sourceRef:
        kind: HelmRepository
        name: github-arc-controller
  interval: 10m0s
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  targetNamespace: github-runner-ctlr
  values:
    metrics:
      controllerManagerAddr: ":8080"
      listenerAddr: ":8080"
      listenerEndpoint: "/metrics"
    serviceAccount:
      # Annotations to add to the service account
      annotations:
        