apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: infra
  namespace: flux-system
spec:
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.8.2
      sourceRef:
        kind: HelmRepository
        name: github-arc-controller
  interval: 10m0s
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  targetNamespace: github-runner-set
  values:
    githubConfigUrl: "https://github.com/pc-gitops/paulc-macbook"
    githubConfigSecret: github-runner-token
    template:
      spec:
        containers:
          - name: runner
            image: pcarlton/infra-runner:0.0.4
            command: ["./run.sh"]
