apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: infra
  namespace: flux-system
spec:
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.8.2
      sourceRef:
        kind: HelmRepository
        name: github-arc-controller
  interval: 10m0s
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  targetNamespace: github-runner-set
  values:
    githubConfigUrl: "https://github.com/pc-gitops/paulc-macbook"
    githubConfigSecret: github-runner-token
    ## maxRunners is the max number of runners the auto scaling runner set will scale up to.
    maxRunners: 3

    ## minRunners is the min number of runners the auto scaling runner set will scale down to.
    minRunners: 1

    containerMode:
      type: kubernetes
      ## the following is required when containerMode.type=kubernetes
      kubernetesModeWorkVolumeClaim:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "hostpath"
        resources:
          requests:
            storage: 1Gi

      kubernetesModeServiceAccount:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::617912315635:role/management-tf-controller

    template:
      spec:
        containers:
          - name: runner
            image: pcarlton/infra-runner:0.0.12
            command: ["./run.sh"]
    #    ServiceAccountName: infra-runner
    # controllerServiceAccount:
    #   namespace: github-runner-set
    #   name: infra-runner
