apiVersion: v1
kind: Namespace
metadata:
  name: capz
---
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: InfrastructureProvider
metadata:
 name: azure
 namespace: capz
spec:
 version: v1.10.0
 deployment:
   containers:
   - args:
       --feature-gates: MachinePool=true,AKSResourceHealth=false,EdgeZone=false
     name: manager