apiVersion: v1
kind: Namespace
metadata:
  name: capi-kubeadm-control-plane-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: ControlPlaneProvider
metadata:
  name: kubeadm
  namespace: capi-kubeadm-control-plane-system
spec:
  version: v1.4.4
  deployment:
    containers:
    - args:
        --feature-gates: MachinePool=true,ClusterResourceSet=true,ClusterTopology=true
      name: manager