apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-runner-token
  namespace: github-runner-set
spec:
  refreshInterval: 1m
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: github-runner-token
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: github-runner-token
