---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: github-runners
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    ${release_type}: ${release_value}
  secretRef:
    name: flux-system
  url: https://github.com/pc-gitops/paulc-macbook
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: github-runners-namespaces
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  prune: true
  wait: true
  path: ./mgmt-cluster/github-runners/namespaces
  sourceRef:
    kind: GitRepository
    name: github-runners
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: github-runners-ctlr
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  prune: true
  wait: true
  dependsOn:
    - name: github-runners-namespaces
  path: ./mgmt-cluster/github-runners/controller
  sourceRef:
    kind: GitRepository
    name: github-runners
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: github-runner-set-config
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  prune: true
  wait: true
  dependsOn:
    - name: github-runners-namespaces
  path: ./mgmt-cluster/github-runners/runner-set/config
  sourceRef:
    kind: GitRepository
    name: github-runners
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: github-runner-set-chart
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  prune: true
  wait: true
  dependsOn:
    - name: github-runner-set-config
  path: ./mgmt-cluster/github-runners/runner-set/chart
  sourceRef:
    kind: GitRepository
    name: github-runners
