apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: ${roleName}
  namespace: ${templateNamespace}
spec:
  interval: 1h
  retryInterval: 20s
  path: ./terraform/cluster-templates/ecr-role
  approvePlan: auto
  storeReadablePlan: human
  destroyResourcesOnDeletion: true
  writeOutputsToSecret:
    name: '${ecrName}-role-config'
  backendConfig:
    customConfiguration: |
      backend "s3" {
        key            = "${mgmtClusterName}/wge/ecr-role/${ecrName}/terraform.tfstate"
        bucket         = "${prefixName}-${awsAccountId}-${awsRegion}-tf-state"
        region         = "${awsRegion}"
        encrypt        = true
        dynamodb_table = "${prefixName}-${awsAccountId}-${awsRegion}-tf-state"
      }
  vars:
    - name: repo_name
      value: ${ecrName}
    - name: role_name
      value: ${roleName}
    - name: cluster_name
      value: ${clusterName}
    - name: sa_namespace
      value: ${templateNamespace}
    - name: service_account
      value: ${serviceAccount}
  varsFrom:
    - kind: ConfigMap
      name: cluster-config
      varsKeys:
        - awsRegion
        - awsAccountId
    - kind: Secret
      name: ${clusterName}-cluster-config
      varsKeys:
        - cluster_oidc_provider_arn
        - cluster_oidc_provider_url
  sourceRef:
    kind: GitRepository
    name: global-config
  runnerPodTemplate:
    spec:
      envFrom:
      - secretRef:
          name: aws-creds
