apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  labels:
    app.kubernetes.io/name: gitopsset
    app.kubernetes.io/instance: gitopsset-namespace
    app.kubernetes.io/part-of: gitopssets-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gitopssets-controller
  name: test-571
  namespace: flux-system
spec:
  serviceAccountName: gitopssets
  generators:
    - gitRepository:
        repositoryRef: flux-system
        directories:
          - path: ./test-571/folders/*
  templates:
    - content:
        kind: Kustomization
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        metadata:
          name: "test-571-{{ .Element.Base }}"
          namespace: test-one
          labels:
            app.kubernetes.io/name: test-571
            app.kubernetes.io/instance: "{{ .Element.Base }}"
        spec:
          interval: 5m
          path: "{{ .Element.Directory }}/{{ .Element.Base }}"
          prune: true
          sourceRef:
            kind: GitRepository
            name: flux-system
            namespace: test-one
          timeout: 1m
          wait: true
          postBuild:
            substitute:
              folder: "{{ .Element.Base }}"
