apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: release-config
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: bases/config
  prune: true
  wait: true
