apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
spec:
  dependsOn:
  - name: flux-components
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  path: ./mgmt-cluster/addons/kyverno
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
  - name: flux-components
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  path: ./mgmt-cluster/addons/cert-manager
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  dependsOn:
  - name: flux-components
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  path: ./mgmt-cluster/addons/nginx
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substitute:
      dnsSuffix: kubernetes.docker.internal
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  dependsOn:
  - name: nginx
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  path: ./mgmt-cluster/addons/metrics-server
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: reloader
  namespace: flux-system
spec:
  dependsOn:
  - name: flux-components
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  path: ./mgmt-cluster/addons/reloader
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-config
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  path: ./mgmt-cluster/cert-config
  prune: true
  wait: true
  dependsOn:
    - name: cert-manager
    - name: nginx
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substitute:
      dnsSuffix: kubernetes.docker.internal
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-config
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  path: ./mgmt-cluster/addons/vault
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substitute:
      dnsSuffix: kubernetes.docker.internal
      storageClass: hostpath
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  dependsOn:
  - name: flux-components
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  path: ./mgmt-cluster/addons/external-secrets
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  path: ./mgmt-cluster/secrets
  prune: true
  wait: true
  dependsOn:
    - name: external-secrets
    - name: cert-config
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substitute:
      dnsSuffix: kubernetes.docker.internal
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dex
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  dependsOn:
    - name: vault
    - name: secrets
    - name: config
  path: ./mgmt-cluster/addons/dex
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: config
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  dependsOn:
    - name: vault
  path: ./mgmt-cluster/config
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  dependsOn:
    - name: dex
  path: ./mgmt-cluster/addons/monitoring/namespace
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-monitoring
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    branch: main
  url: https://github.com/pc-gitops/flux2-monitoring
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-mon-ctlr
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  dependsOn:
  - name: monitoring
  path: ./monitoring/controllers/kube-prometheus-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-monitoring
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  dependsOn:
    - name: flux-mon-ctlr
  path: ./mgmt-cluster/addons/monitoring/prometheus
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prom-alert
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  dependsOn:
    - name: prometheus
  path: ./mgmt-cluster/addons/monitoring/prom-alert
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  dependsOn:
    - name: prom-alert
  path: ./mgmt-cluster/addons/monitoring/grafana
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  dependsOn:
    - name: grafana
  path: ./mgmt-cluster/addons/monitoring/loki
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: graf-agent
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  dependsOn:
    - name: loki
  path: ./mgmt-cluster/addons/monitoring/graf-agent
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-mon-config
  namespace: flux-system
spec:
  dependsOn:
  - name: graf-agent
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  path: ./monitoring/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-monitoring
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  dependsOn:
    - name: dex
  path: ./mgmt-cluster/bases/flux
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
