apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: github-runners
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: mgmt-cluster/github-runners/flux
  prune: true
  wait: true
  dependsOn:
    - name: release-config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: github-runners-release