apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: keycloak-client-realms-${enterpriseId:0:8}
  namespace: test-one
  labels:
    add-orgs: true
spec:
  interval: 1m
  approvePlan: auto
  storeReadablePlan: human
  path: ./test-603/keycloak/empower-client-realms
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: test-one
  backendConfig:
    customConfiguration: |
      backend "azurerm" {
        storage_account_name = "some storage account"
        container_name       = "some container"
        key                  = "some state file"
        resource_group_name  = "some rg"
        subscription_id      = "some sub ID"
        tenant_id            = "some tenant ID"
      }
  vars:
    - name: tenant_id
      value: ${tenantId}
    - name: subscription_id
      value: ${subscriptionId}
    - name: enterprise
      value: ${enterprise}
    - name: enterprise_guid
      value: ${enterpriseId}
    - name: internal_environment
      value: ${centralEnv}
    - name: keycloak_url
      value: ${keycloakUrl}
  varsFrom:
    - kind: Secret
      name: empower-sso-client-secret-realm
    - kind: Secret
      name: enterprise-sso-client-secret-realm
    - kind: Secret
      name: keycloak-provider-client-secret   
    - kind: Secret
      name: whizbang-solution-internal-svc-creds  
  runnerPodTemplate:
    spec:
      env:
        - name: ARM_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: whizbang-solution-internal-svc-prnc
              key: value
        - name: ARM_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: whizbang-solution-internal-svc-prnc-pwd
              key: value
