# kustomization.yaml
resources:
- tf.yaml
patches:
  - patch: |
      - op: add
        path: "/spec/vars/6/value"
        value: 
          - org1
          - org2
    target:
      group: infra.contrib.fluxcd.io
      version: v1alpha2
      kind: Terraform
      labelSelector: "app.kubernetes.io/component=keycloak-client-realms-2e63d88d"
