name: Infrastructure Management
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  infra:
    runs-on: posdev-pcarlton2-pc-gitops-paulc-macbook
    container:
      image: 617912315635.dkr.ecr.us-west-2.amazonaws.com/runner:0.1.11
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          cache: true # setup-go has built-in mod caching: https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs
      - name: build
        run: go build ./...
