name: Infrastructure Management
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  infra:
    runs-on: github-runner-set-infra
    container:
      image: pcarlton/infra-runner:0.0.12
    steps:
    - run: /home/runner/bin/infra.sh --debug
